// <auto-generated />
using System;
using Escola.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Escola.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EscolaDbContext))]
    [Migration("20260921235429_AddFichaSaude")]
    partial class AddFichaSaude
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Escola.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Escola.Domain.Entities.AlunoResponsavel", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutorizadoParaBuscar")
                        .HasColumnType("boolean");

                    b.Property<bool>("ResponsavelFinanceiro")
                        .HasColumnType("boolean");

                    b.HasKey("AlunoId", "ResponsavelId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("AlunoResponsaveis");
                });

            modelBuilder.Entity("Escola.Domain.Entities.FichaSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alergias")
                        .HasColumnType("text");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AutorizaUsoImagem")
                        .HasColumnType("boolean");

                    b.Property<string>("CondicoesSaude")
                        .HasColumnType("text");

                    b.Property<string>("ContatoEmergenciaNome")
                        .HasColumnType("text");

                    b.Property<string>("ContatoEmergenciaTelefone")
                        .HasColumnType("text");

                    b.Property<string>("MedicamentosEmUso")
                        .HasColumnType("text");

                    b.Property<string>("PediatraNome")
                        .HasColumnType("text");

                    b.Property<string>("PediatraTelefone")
                        .HasColumnType("text");

                    b.Property<string>("PlanoSaude")
                        .HasColumnType("text");

                    b.Property<string>("RestricoesAlimentares")
                        .HasColumnType("text");

                    b.Property<string>("TipoSanguineo")
                        .HasColumnType("text");

                    b.Property<bool>("VacinacaoEmDia")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("FichasSaude");
                });

            modelBuilder.Entity("Escola.Domain.Entities.FotoRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegistroRotinaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroRotinaId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("Escola.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Acao")
                        .HasColumnType("integer");

                    b.Property<string>("Detalhe")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EntidadeTipo", "EntidadeId");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("Escola.Domain.Entities.RegistroRotina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("AlunoId", "RegistradoEm");

                    b.ToTable("RegistrosRotina");

                    b.HasDiscriminator<string>("Categoria").HasValue("RegistroRotina");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Escola.Domain.Entities.Responsavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("Escola.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("HorarioEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HorarioSaida")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Periodo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Escola.Domain.Entities.TurmaEducador", b =>
                {
                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("TurmaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TurmaEducadores");
                });

            modelBuilder.Entity("Escola.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Papel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Escola.Domain.Entities.RegistroAlimentacao", b =>
                {
                    b.HasBaseType("Escola.Domain.Entities.RegistroRotina");

                    b.Property<int>("Refeicao")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Alimentacao");
                });

            modelBuilder.Entity("Escola.Domain.Entities.RegistroHigiene", b =>
                {
                    b.HasBaseType("Escola.Domain.Entities.RegistroRotina");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Higiene");
                });

            modelBuilder.Entity("Escola.Domain.Entities.RegistroHumor", b =>
                {
                    b.HasBaseType("Escola.Domain.Entities.RegistroRotina");

                    b.Property<int>("Humor")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Humor");
                });

            modelBuilder.Entity("Escola.Domain.Entities.RegistroMomento", b =>
                {
                    b.HasBaseType("Escola.Domain.Entities.RegistroRotina");

                    b.HasDiscriminator().HasValue("Momento");
                });

            modelBuilder.Entity("Escola.Domain.Entities.RegistroSono", b =>
                {
                    b.HasBaseType("Escola.Domain.Entities.RegistroRotina");

                    b.Property<TimeOnly?>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.HasDiscriminator().HasValue("Sono");
                });

            modelBuilder.Entity("Escola.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("Escola.Domain.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Escola.Domain.Entities.AlunoResponsavel", b =>
                {
                    b.HasOne("Escola.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Responsaveis")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Escola.Domain.Entities.Responsavel", "Responsavel")
                        .WithMany("Alunos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Escola.Domain.Entities.FichaSaude", b =>
                {
                    b.HasOne("Escola.Domain.Entities.Aluno", "Aluno")
                        .WithOne()
                        .HasForeignKey("Escola.Domain.Entities.FichaSaude", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("Escola.Domain.Entities.FotoRegistro", b =>
                {
                    b.HasOne("Escola.Domain.Entities.RegistroRotina", "RegistroRotina")
                        .WithMany("Fotos")
                        .HasForeignKey("RegistroRotinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroRotina");
                });

            modelBuilder.Entity("Escola.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("Escola.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Escola.Domain.Entities.RegistroRotina", b =>
                {
                    b.HasOne("Escola.Domain.Entities.Aluno", "Aluno")
                        .WithMany("RegistrosRotina")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Escola.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("Escola.Domain.Entities.TurmaEducador", b =>
                {
                    b.HasOne("Escola.Domain.Entities.Turma", "Turma")
                        .WithMany("Educadores")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Escola.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Turmas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Escola.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Escola.Domain.Entities.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Escola.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("RegistrosRotina");

                    b.Navigation("Responsaveis");
                });

            modelBuilder.Entity("Escola.Domain.Entities.RegistroRotina", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Escola.Domain.Entities.Responsavel", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("Escola.Domain.Entities.Turma", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Educadores");
                });

            modelBuilder.Entity("Escola.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Turmas");
                });
#pragma warning restore 612, 618
        }
    }
}
